[package]
name = "obsidian-rust-interface"
version = "0.2.9"
edition = "2021"

[dependencies]
itertools = "^0.11"
serde = { version = "^1", features = ["derive"] }
serde_yaml = "^0.9"
thiserror = "^1"
tracing = "^0.1"
walkdir = "^2.3.3"
